#!/usr/bin/env node
/**
 * Build-time network selection. Writes src/lib/generated/network.ts containing ONLY the chain the
 * app is built for (NEXT_PUBLIC_CHAIN_ID, default 4663 = Robinhood Chain mainnet): its viem chain
 * definition, gas-faucet links and contract deployment (or null before launch). Nothing about other
 * chains (e.g. testnet addresses or RPCs) ends up in the client bundle.
 *
 * Runs automatically before dev / build / typecheck / lint (npm pre-scripts).
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// npm pre-scripts run before Next loads .env files, so read them the same way Next would.
for (const f of [".env.local", ".env"]) {
  const p = join(root, f);
  if (!existsSync(p)) continue;
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}
const env = (k) => process.env[k] || "";

const CHAINS = {
  4663: {
    chain: {
      id: 4663,
      name: "Robinhood Chain",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [env("NEXT_PUBLIC_ROBINHOOD_MAINNET_RPC_URL") || "https://rpc.mainnet.chain.robinhood.com"] } },
      blockExplorers: { default: { name: "Blockscout", url: "https://robinhoodchain.blockscout.com" } },
    },
    testnet: false,
    gasFaucets: [],
  },
  46630: {
    chain: {
      id: 46630,
      name: "Robinhood Chain Testnet",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [env("NEXT_PUBLIC_ROBINHOOD_RPC_URL") || "https://rpc.testnet.chain.robinhood.com"] } },
      blockExplorers: { default: { name: "Blockscout", url: "https://explorer.testnet.chain.robinhood.com" } },
      testnet: true,
    },
    testnet: true,
    gasFaucets: [
      { label: "Robinhood Chain faucet", url: "https://faucet.testnet.chain.robinhood.com/" },
      { label: "Alchemy faucet", url: "https://www.alchemy.com/faucets/robinhood-testnet" },
    ],
  },
  31337: {
    chain: {
      id: 31337,
      name: "Anvil (local)",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [env("NEXT_PUBLIC_LOCAL_RPC_URL") || "http://127.0.0.1:8545"] } },
      testnet: true,
    },
    testnet: true,
    gasFaucets: [],
  },
  84532: {
    chain: {
      id: 84532,
      name: "Base Sepolia",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [env("NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL") || "https://sepolia.base.org"] } },
      blockExplorers: { default: { name: "Basescan", url: "https://sepolia.basescan.org" } },
      testnet: true,
    },
    testnet: true,
    gasFaucets: [{ label: "Base Sepolia faucets", url: "https://docs.base.org/base-chain/tools/network-faucets" }],
  },
};

const id = Number(env("NEXT_PUBLIC_CHAIN_ID") || 4663);
const net = CHAINS[id];
if (!net) throw new Error(`select-network: unsupported NEXT_PUBLIC_CHAIN_ID ${id}`);

const depFile = join(root, "src", "lib", "generated", "deployments.json");
const all = existsSync(depFile) ? JSON.parse(readFileSync(depFile, "utf8")) : {};
const deployment = all[id] ?? null;

const out = `// AUTO-GENERATED by scripts/select-network.mjs for chain ${id}. Do not edit; not committed.
import type { Chain } from "viem";
import type { Deployment } from "../deployment-types";

export const NETWORK_CHAIN: Chain = ${JSON.stringify(net.chain, null, 2)};
export const NETWORK_IS_TESTNET = ${net.testnet};
export const NETWORK_GAS_FAUCETS: { label: string; url: string }[] = ${JSON.stringify(net.gasFaucets)};
export const NETWORK_DEPLOYMENT: Deployment | null = ${JSON.stringify(deployment, null, 2)};
export const NETWORK_HAS_FAUCET = ${Boolean(deployment?.faucet)};
`;
writeFileSync(join(root, "src", "lib", "generated", "network.ts"), out);
// The faucet page body is wired in only when this chain has a faucet, so other builds never compile it.
writeFileSync(
  join(root, "src", "lib", "generated", "faucet-body.ts"),
  deployment?.faucet
    ? `// AUTO-GENERATED by scripts/select-network.mjs. Do not edit; not committed.\nexport { default } from "@/components/faucet/faucet-page";\n`
    : `// AUTO-GENERATED by scripts/select-network.mjs. Do not edit; not committed.\nconst FaucetPageBody: (() => React.ReactNode) | null = null;\nexport default FaucetPageBody;\n`,
);
console.log(`select-network: chain ${id} (${net.chain.name}), deployment ${deployment ? "found" : "none (pre-launch)"}`);
